// Generated by gencpp from file msgsrv_basics_p/WarningSwitch.msg
// DO NOT EDIT!


#ifndef MSGSRV_BASICS_P_MESSAGE_WARNINGSWITCH_H
#define MSGSRV_BASICS_P_MESSAGE_WARNINGSWITCH_H

#include <ros/service_traits.h>


#include <msgsrv_basics_p/WarningSwitchRequest.h>
#include <msgsrv_basics_p/WarningSwitchResponse.h>


namespace msgsrv_basics_p
{

struct WarningSwitch
{

typedef WarningSwitchRequest Request;
typedef WarningSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WarningSwitch
} // namespace msgsrv_basics_p


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgsrv_basics_p::WarningSwitch > {
  static const char* value()
  {
    return "6cf6f195cf922f022d7cdea6a7f7d821";
  }

  static const char* value(const ::msgsrv_basics_p::WarningSwitch&) { return value(); }
};

template<>
struct DataType< ::msgsrv_basics_p::WarningSwitch > {
  static const char* value()
  {
    return "msgsrv_basics_p/WarningSwitch";
  }

  static const char* value(const ::msgsrv_basics_p::WarningSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::msgsrv_basics_p::WarningSwitchRequest> should match
// service_traits::MD5Sum< ::msgsrv_basics_p::WarningSwitch >
template<>
struct MD5Sum< ::msgsrv_basics_p::WarningSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgsrv_basics_p::WarningSwitch >::value();
  }
  static const char* value(const ::msgsrv_basics_p::WarningSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgsrv_basics_p::WarningSwitchRequest> should match
// service_traits::DataType< ::msgsrv_basics_p::WarningSwitch >
template<>
struct DataType< ::msgsrv_basics_p::WarningSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::msgsrv_basics_p::WarningSwitch >::value();
  }
  static const char* value(const ::msgsrv_basics_p::WarningSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgsrv_basics_p::WarningSwitchResponse> should match
// service_traits::MD5Sum< ::msgsrv_basics_p::WarningSwitch >
template<>
struct MD5Sum< ::msgsrv_basics_p::WarningSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgsrv_basics_p::WarningSwitch >::value();
  }
  static const char* value(const ::msgsrv_basics_p::WarningSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgsrv_basics_p::WarningSwitchResponse> should match
// service_traits::DataType< ::msgsrv_basics_p::WarningSwitch >
template<>
struct DataType< ::msgsrv_basics_p::WarningSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::msgsrv_basics_p::WarningSwitch >::value();
  }
  static const char* value(const ::msgsrv_basics_p::WarningSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGSRV_BASICS_P_MESSAGE_WARNINGSWITCH_H
