// Generated by gencpp from file msgsrv_basics_p/WarningSwitchResponse.msg
// DO NOT EDIT!


#ifndef MSGSRV_BASICS_P_MESSAGE_WARNINGSWITCHRESPONSE_H
#define MSGSRV_BASICS_P_MESSAGE_WARNINGSWITCHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace msgsrv_basics_p
{
template <class ContainerAllocator>
struct WarningSwitchResponse_
{
  typedef WarningSwitchResponse_<ContainerAllocator> Type;

  WarningSwitchResponse_()
    : res_msg()  {
    }
  WarningSwitchResponse_(const ContainerAllocator& _alloc)
    : res_msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _res_msg_type;
  _res_msg_type res_msg;





  typedef boost::shared_ptr< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WarningSwitchResponse_

typedef ::msgsrv_basics_p::WarningSwitchResponse_<std::allocator<void> > WarningSwitchResponse;

typedef boost::shared_ptr< ::msgsrv_basics_p::WarningSwitchResponse > WarningSwitchResponsePtr;
typedef boost::shared_ptr< ::msgsrv_basics_p::WarningSwitchResponse const> WarningSwitchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator1> & lhs, const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res_msg == rhs.res_msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator1> & lhs, const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgsrv_basics_p

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e59d47478f843b11a9955719c87001a";
  }

  static const char* value(const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e59d47478f843b1ULL;
  static const uint64_t static_value2 = 0x1a9955719c87001aULL;
};

template<class ContainerAllocator>
struct DataType< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgsrv_basics_p/WarningSwitchResponse";
  }

  static const char* value(const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String res_msg\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WarningSwitchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgsrv_basics_p::WarningSwitchResponse_<ContainerAllocator>& v)
  {
    s << indent << "res_msg: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.res_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGSRV_BASICS_P_MESSAGE_WARNINGSWITCHRESPONSE_H
